In [38]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

In [4]:
pwd   #present working directory

'C:\\Users\\CHROMIUM\\Desktop\\PROJECT\\LinearRegression'

In [5]:
# !pip install  lib   - installting in jupyter

In [6]:
ds = pd.read_csv("Salary_Data.csv")

In [7]:
ds.head()

YearsExperience   Salary
0              1.1  39343.0
1              1.3  46205.0
2              1.5  37731.0
3              2.0  43525.0
4              2.2  39891.0

In [8]:
x = [[23,54,44],[66,77,88]]

In [9]:
df1 = pd.DataFrame(x, index=['Ramseh','Suresh'], columns =['maths','physics','chemistry'])
#creating index in rows and column from list

In [10]:
df1

maths  physics  chemistry
Ramseh     23       54         44
Suresh     66       77         88

In [11]:
d = {"Hari":[55,97,67],"Krishna":[99,66,76]}

In [12]:
df2  = pd.DataFrame(d)  #creating a dataframe using dictionary

In [13]:
df2

Hari  Krishna
0    55       99
1    97       66
2    67       76

In [14]:
df2["Hari"][1] #without iloc slicing

97

In [15]:
#ILOC gives the indexing using default indexing

In [16]:
df2.iloc[1,0]

97

In [17]:
df2.iloc[1][0]

97

In [24]:
x = ds.iloc[:,:-1].values
x

array([[ 1.1],
       [ 1.3],
       [ 1.5],
       [ 2. ],
       [ 2.2],
       [ 2.9],
       [ 3. ],
       [ 3.2],
       [ 3.2],
       [ 3.7],
       [ 3.9],
       [ 4. ],
       [ 4. ],
       [ 4.1],
       [ 4.5],
       [ 4.9],
       [ 5.1],
       [ 5.3],
       [ 5.9],
       [ 6. ],
       [ 6.8],
       [ 7.1],
       [ 7.9],
       [ 8.2],
       [ 8.7],
       [ 9. ],
       [ 9.5],
       [ 9.6],
       [10.3],
       [10.5]])

In [23]:
x.ndim

2

In [28]:
y = ds.iloc[:,-1].values   #here using values for removing index from the uotput
y

array([ 39343.,  46205.,  37731.,  43525.,  39891.,  56642.,  60150.,
        54445.,  64445.,  57189.,  63218.,  55794.,  56957.,  57081.,
        61111.,  67938.,  66029.,  83088.,  81363.,  93940.,  91738.,
        98273., 101302., 113812., 109431., 105582., 116969., 112635.,
       122391., 121872.])

In [29]:
y.ndim

1

In [34]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.2, random_state = 1)

In [36]:
x_train,x_test,y_train,y_test

(array([[ 9.5],
        [ 2. ],
        [ 8.7],
        [ 7.9],
        [ 8.2],
        [ 2.2],
        [ 1.5],
        [ 9. ],
        [ 3. ],
        [ 5.9],
        [ 4.1],
        [ 3.2],
        [ 9.6],
        [ 1.3],
        [ 5.1],
        [ 1.1],
        [ 4.9],
        [10.5],
        [10.3],
        [ 3.7],
        [ 3.2],
        [ 4. ],
        [ 4. ],
        [ 2.9]]),
 array([[5.3],
        [7.1],
        [3.9],
        [6. ],
        [4.5],
        [6.8]]),
 array([116969.,  43525., 109431., 101302., 113812.,  39891.,  37731.,
        105582.,  60150.,  81363.,  57081.,  54445., 112635.,  46205.,
         66029.,  39343.,  67938., 121872., 122391.,  57189.,  64445.,
         56957.,  55794.,  56642.]),
 array([83088., 98273., 63218., 93940., 61111., 91738.]))

In [39]:
reg  = LinearRegression()  #creating an instance

In [40]:
reg.fit(x_train,y_train)   #in this reg convert into a model fitted by x_train, and y_train

LinearRegression()

In [42]:
y_pred = reg.predict(x_test)
y_pred

array([75074.50510972, 91873.8056381 , 62008.38247653, 81607.56642631,
       67608.14931932, 89073.92221671])

In [43]:
x_test

array([[5.3],
       [7.1],
       [3.9],
       [6. ],
       [4.5],
       [6.8]])

In [44]:
y_test

array([83088., 98273., 63218., 93940., 61111., 91738.])

In [ ]:
plt.scatter(x_test,y_test,color = 'blue')
plt.plot(x_train)
